#pragma once

#define WINDOW_CLASS_NAME L"SMBGameWindow"
#define MAIN_WINDOW_TITLE L"Super Mario Bros 3"

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 480 

#define D3DCOLOR_BLACK D3DCOLOR_XRGB(0, 0, 0)
#define D3DCOLOR_WHITE D3DCOLOR_XRGB(255, 255, 255)

#define MAX_FRAME_RATE 120


